### ISSUE TITLE
Both GIT links below the video redirect to a 404 error page

### ISSUE THREAD

**Issue by doosemavis** [learn-co-curriculum/fe-git-basics#2]
Hope this is helpful! 

![Screen Shot 2021-02-22 at 7 22 18 AM](https://user-images.githubusercontent.com/70960898/108714093-b9945580-74de-11eb-9414-673e1e327c0c.png)

**Comment by lizbur10** [comment]
Hi @doosemavis ! Thanks for bringing this to our attention - the links have been updated.

Congrats on graduating!!
